using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace csharp_practice
{
    internal class EUL_2
    {
        public static void Run()
        {
            //Project EULER Problem 2
            /* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
            By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
            */

            long maxNumber = 4000000;
            long current = 1, previous = 0, temp = 0;
            long sum = 0;
            while (current < maxNumber)
            {
                if (current % 2 == 0)
                {
                    sum += current;
                }
                temp = current + previous;
                previous = current;
                current = temp;
            }

            Console.WriteLine(sum);
        }

    }
}
